## Predict the passed and failed  data

### Using Logistic regression algorithm

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [4]:
A=pd.read_csv("C:\\Users\\intel\\Downloads\\WL_task2_ProdData_2023_versionD.csv")
A

,Unnamed: 0,Date,Energy,Resistance,Current,Voltage,Power,uipvalue,weldpoint,score,prediction,year,month,day,id
0,16645,2023-03-10 16:06:05.180,5279.587891,272.0,7.10,1.88,13342.919922,80,T0391,8.137701,Passed,2023,3,10,Train
1,16650,2023-03-10 16:06:59.390,5284.775879,270.0,7.13,1.84,13123.620117,96,T0391,15.128845,Passed,2023,3,10,Train
2,16651,2023-03-10 16:00:49.570,5229.563965,267.0,7.15,1.85,13218.250000,69,T0391,39.734211,Failed,2023,3,10,Train
3,16660,2023-03-10 16:44:37.850,5402.745117,273.0,7.16,1.90,13602.860352,93,T0391,16.287536,Passed,2023,3,10,Train
4,16661,2023-03-10 16:45:25.860,5341.735840,274.0,7.10,1.89,13413.139648,95,T0391,0.707636,Passed,2023,3,10,Train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8448,94288,2023-08-08 14:11:31.360,5510.055176,277.0,7.16,1.93,13828.259766,107,T0391,14.094838,Passed,2023,8,8,Test
8449,94289,2023-08-08 14:00:20.180,5404.756836,277.0,7.09,1.93,13691.419922,108,T0391,3.364030,Passed,2023,8,8,Test
8450,94290,2023-08-08 14:01:13.470,5384.125000,276.0,7.10,1.92,13623.940430,105,T0391,2.171779,Failed,2023,8,8,Test
8451,94291,2023-08-08 14:06:30.710,5395.432129,277.0,7.10,1.91,13556.799805,104,T0391,1.702148,Passed,2023,8,8,Test
8452,94292,2023-08-08 14:07:19.430,5414.668945,278.0,7.10,1.93,13703.000000,104,T0391,3.865788,Passed,2023,8,8,Test

In [5]:
# sklearn import preprocessing                   
#label_encoder= preprocessing.LabelEncoder()
#A['prediction'] = label_encoder.fit_transform(A['prediction'])     
#A['prediction'].value_counts

In [6]:
A

,Unnamed: 0,Date,Energy,Resistance,Current,Voltage,Power,uipvalue,weldpoint,score,prediction,year,month,day,id
0,16645,2023-03-10 16:06:05.180,5279.587891,272.0,7.10,1.88,13342.919922,80,T0391,8.137701,Passed,2023,3,10,Train
1,16650,2023-03-10 16:06:59.390,5284.775879,270.0,7.13,1.84,13123.620117,96,T0391,15.128845,Passed,2023,3,10,Train
2,16651,2023-03-10 16:00:49.570,5229.563965,267.0,7.15,1.85,13218.250000,69,T0391,39.734211,Failed,2023,3,10,Train
3,16660,2023-03-10 16:44:37.850,5402.745117,273.0,7.16,1.90,13602.860352,93,T0391,16.287536,Passed,2023,3,10,Train
4,16661,2023-03-10 16:45:25.860,5341.735840,274.0,7.10,1.89,13413.139648,95,T0391,0.707636,Passed,2023,3,10,Train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8448,94288,2023-08-08 14:11:31.360,5510.055176,277.0,7.16,1.93,13828.259766,107,T0391,14.094838,Passed,2023,8,8,Test
8449,94289,2023-08-08 14:00:20.180,5404.756836,277.0,7.09,1.93,13691.419922,108,T0391,3.364030,Passed,2023,8,8,Test
8450,94290,2023-08-08 14:01:13.470,5384.125000,276.0,7.10,1.92,13623.940430,105,T0391,2.171779,Failed,2023,8,8,Test
8451,94291,2023-08-08 14:06:30.710,5395.432129,277.0,7.10,1.91,13556.799805,104,T0391,1.702148,Passed,2023,8,8,Test
8452,94292,2023-08-08 14:07:19.430,5414.668945,278.0,7.10,1.93,13703.000000,104,T0391,3.865788,Passed,2023,8,8,Test

### Split the data into features (X) and labels (y)

In [7]:
x=A[['Energy','Resistance','Current','Voltage','Power','uipvalue','year','month','day']] 
y=A['prediction']

### Split the data into training and testing sets

In [8]:
from sklearn.linear_model import LogisticRegression                #importing the model from sklearn
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

### Create and train/fit a logistic regression model

In [9]:
lr= LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

### Predict labels on the test set

In [10]:
lrpred = lr.predict(x_test)
lrpred

array(['Passed', 'Passed', 'Passed', ..., 'Passed', 'Failed', 'Passed'],
      dtype=object)

### Evaluate accuracy (optional)

In [11]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, lrpred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7791798107255521

In [12]:
print(lrpred)

['Passed' 'Passed' 'Passed' ... 'Passed' 'Failed' 'Passed']

In [13]:
#Create a DataFrame with true labels and predicted labels
df_results = pd.DataFrame({'True Labels': y_test, 'Predicted Labels': lrpred})
df_results
#print(df_results.head())

     True Labels Predicted Labels
1633      Passed           Passed
6045      Passed           Passed
1526      Failed           Passed
8002      Passed           Passed
2560      Passed           Passed
...          ...              ...
4507      Failed           Passed
6840      Passed           Passed
3723      Passed           Passed
8289      Failed           Failed
1872      Passed           Passed

[2536 rows x 2 columns]

In [14]:
#Train=A[A['id']]='Train'
#Test=A[A['id']]='Test'
#lr1= LogisticRegression()
#lr1.fit(x_train, y_train)
#lrpred1 = lr.predict(x_test)
#print(lrpred1)

### Predict the Resistance(by using Energy,Current,Voltage,Power)

### linear regression model

In [15]:
A

,Unnamed: 0,Date,Energy,Resistance,Current,Voltage,Power,uipvalue,weldpoint,score,prediction,year,month,day,id
0,16645,2023-03-10 16:06:05.180,5279.587891,272.0,7.10,1.88,13342.919922,80,T0391,8.137701,Passed,2023,3,10,Train
1,16650,2023-03-10 16:06:59.390,5284.775879,270.0,7.13,1.84,13123.620117,96,T0391,15.128845,Passed,2023,3,10,Train
2,16651,2023-03-10 16:00:49.570,5229.563965,267.0,7.15,1.85,13218.250000,69,T0391,39.734211,Failed,2023,3,10,Train
3,16660,2023-03-10 16:44:37.850,5402.745117,273.0,7.16,1.90,13602.860352,93,T0391,16.287536,Passed,2023,3,10,Train
4,16661,2023-03-10 16:45:25.860,5341.735840,274.0,7.10,1.89,13413.139648,95,T0391,0.707636,Passed,2023,3,10,Train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8448,94288,2023-08-08 14:11:31.360,5510.055176,277.0,7.16,1.93,13828.259766,107,T0391,14.094838,Passed,2023,8,8,Test
8449,94289,2023-08-08 14:00:20.180,5404.756836,277.0,7.09,1.93,13691.419922,108,T0391,3.364030,Passed,2023,8,8,Test
8450,94290,2023-08-08 14:01:13.470,5384.125000,276.0,7.10,1.92,13623.940430,105,T0391,2.171779,Failed,2023,8,8,Test
8451,94291,2023-08-08 14:06:30.710,5395.432129,277.0,7.10,1.91,13556.799805,104,T0391,1.702148,Passed,2023,8,8,Test
8452,94292,2023-08-08 14:07:19.430,5414.668945,278.0,7.10,1.93,13703.000000,104,T0391,3.865788,Passed,2023,8,8,Test

In [16]:
x=A[['Energy','Current','Voltage','Power']] 
y=A['Resistance']

In [17]:
from sklearn.model_selection import train_test_split
x1_train ,x1_test, y1_train, y1_test = train_test_split (x,y,test_size=0.3,random_state=0)

In [18]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x1_train, y1_train)
lr= reg.predict(x1_test)
reg.score(x1_train,y1_train)

0.9351944149851104

In [19]:
print(lr)

[277.08384054 273.22884167 271.98207727 ... 272.34602224 271.7010301
 276.32872309]

In [20]:
result = pd.DataFrame({'Actual Resistance': y1_test, 'Predicted Resistance': lr})
print(result)

      Actual Resistance  Predicted Resistance
1633              278.0            277.083841
6045              274.0            273.228842
1526              270.0            271.982077
8002              272.0            271.936948
2560              277.0            277.493247
...                 ...                   ...
4507              269.0            269.226431
6840              273.0            272.336580
3723              273.0            272.346022
8289              271.0            271.701030
1872              276.0            276.328723

[2536 rows x 2 columns]